[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[hooks.yapf]
priority = 30

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort]
priority = 50

[hooks.isort.kwargs]
indent = "		"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "apeye_core",
    "attrs",
    "coincidence",
    "coverage",
    "coverage_pyver_pragma",
    "dom_toml",
    "domdf_python_tools",
    "importlib_metadata",
    "license_expression",
    "natsort",
    "nh3",
    "packaging",
    "pyproject_examples",
    "pytest",
    "pytest_cov",
    "pytest_randomly",
    "pytest_timeout",
    "shippinglabel",
    "tomli",
    "typing_extensions",
]
known_first_party = [ "pyproject_parser",]

[config]
indent = "	"
line_length = 115
